##Recuperar todas las peliculas
GET http://localhost:1234/movies

##Recuperar una pelicula por id
GET http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

##Recuperar todas las peliculas por genero
GET http://localhost:1234/movies?genre=action

##Crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "Fast and Furious 5",
  "year": 2023,
  "director": "John Doe",
  "duration": 120,
  "poster": "https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  "genre": ["Drama", "Action"]
  
}

##Actualizar una pelicula por id
PATCH http://localhost:1234/movies/f7b3738d-c8e8-46ee-bb0d-5f69a185a7d4
Content-Type: application/json

{
  "year": 2010
}


#Eliminar una pelicula por id
DELETE http://localhost:1234/movies/f7b3738d-c8e8-46ee-bb0d-5f69a185a7d4